### ISSUE TITLE
Navigating away from map before it finishes loading measurements crashes app

### ISSUE THREAD

**Issue by jasonccox** [CellWatch/cellwatch-app#65]
## Steps to reproduce

1. Take several measurements in the app.
2. Close the app.
3. Open the app.
4. Before the map loads the measurements in your current hexagon (i.e., before it turns green), click the `+ Measure` button to take a measurement.
5. Wait for the crash.

## Expected behavior

The app doesn't crash.

## Actual behavior

The app crashed.

## Details

- App version: 1.0.0-alpha.5
- Device ID: 6ff77dcb-fecb-43dc-a937-14d32383ea94
- Date/time: 29 Apr 2024 @ 16:28 EDT

## More info

Logs:

```
2024-04-29 16:28:17.891 10682-10682 MapFragment             edu.gatech.cc.cellwatch              I  Determining if we have a match: false and false
2024-04-29 16:28:17.933 10682-10682 MapFragment             edu.gatech.cc.cellwatch              I  []
2024-04-29 16:28:17.933 10682-10682 MapFragment             edu.gatech.cc.cellwatch              I  Determining if we have a match: false and false
2024-04-29 16:28:18.057 10682-10682 MapFragment             edu.gatech.cc.cellwatch              I  [MeasurementGroup(latency=Measurement(id=c2e9af14-c5f0-484e-b3c4-a8ed89fc746b, groupId=a8936025-09c4-481e-80d2-763c604e001a, campaignId=null, sessionId=null, deviceId=6ff77dcb-fecb-43dc-a937-14d32383ea94, deviceManufacturer=motorola, deviceModel=moto_g(7), deviceOsName=Android, deviceOsVersion=10, appName=CellWatch, provider=ting, type=latency, timestamp=2024-04-11T12:26:30.370Z, duration=6053000, scheduled=false, success=true, carrierAggregation=false, networkConnected=true, networkAvailable=true, networkRoaming=false, simMcc=310, simMnc=240, netMcc=310, netMnc=260, extraData=null, createdOn=2024-04-11T12:27:09.091Z, updatedOn=2024-04-11T12:27:09.091Z, uploadDownloadData=null, latencyData=LatencyData(id=854e82ce-c45e-4183-a861-cfa910c08e4c, measurementId=c2e9af14-c5f0-484e-b3c4-a8ed89fc746b, rtt=38604, jitter=686596, sent=215, received=215, servers=[msak-mlab2-ord03.mlab-oti.measurement-lab.org], createdOn=null, updatedOn=null), locations=[Location(id=df2e4988-3dcf-48c3-a107-f22ff6e7bd7a, timestamp=2024-04-11T12:26:29.955Z, lat=33.8149972, lon=-84.5747246, accuracy=20.0, speed=null, speedAccuracy=1.5, heading=null, measurementId=c2e9af14-c5f0-484e-b3c4-a8ed89fc746b, createdOn=null, updatedOn=null), Location(id=601f6b2d-65e7-40d1-9f14-10faed47cee6, timestamp=2024-04-11T12:26:29.955Z, lat=33.8149972, lon=-84.5747246, accuracy=20.0, speed=null, speedAccuracy=1.5, heading=null, measurementId=c2e9af14-c5f0-484e-b3c4-a8ed89fc746b, createdOn=null, updatedOn=null)], cells=[Cell(id=49c2ce58-2742-4b17-9641-e48964a0f489, timestamp=2024-04-11T12:26:29.378Z, cellId=223378178, physicalCellId=298, cellConnection=0, networkGeneration=4G, networkSubtype=LTE, signalStrength=-86, rssi=-57, rsrp=-86, rsrq=-8, sinr=null, csiRsrp=null, csiRsrq=null, csiSinr=null, cqi=null, spectrumBand=null, spectrumBandwidth=20.0, arfcn=66786, measurementId=c2e9af14-c5f0-484e-b3c4-a8ed89fc746b, createdOn=null, updatedOn=null), Cell(id=4b51a14a-06ad-4e28-a69c-ad70d59b16a2, timestamp=2024-04-11T12:26:29.378Z, cellId=null, physicalCellId=null, cellConnection=0, networkGeneration=2G, networkSubtype=GSM, signalStrength=-113, rssi=null, rsrp=null, rsrq=null, sinr=null, csiRsrp=null, csiRsrq=null, csiSinr=null, cqi=null, spectrumBand=null, spectrumBandwidth=null, arfcn=710, measurementId=c2e9af14-c5f0-484e-b3c4-a8ed89fc746b, createdOn=null, updatedOn=null), Cell(id=92d91c0a-674d-4165-bd45-118ecbf70646, timestamp=2024-04-11T12:26:29.377Z, cellId=null, physicalCellId=null, cellConnection=0, networkGeneration=2G, networkSubtype=GSM, signalStrength=-113, rssi=null, rsrp=null, rsrq=null, sinr=null, csiRsrp=null, csiRsrq=null, csiSinr=null, cqi=null, spectrumBand=null, spectrumBandwidth=null, arfcn=709, measurementId=c2e9af14-c5f0-484e-b3c4-a8ed89fc746b, createdOn=null, updatedOn=null), Cell(id=e2070826-bd33-4a65-95e1-9ce1ea3056c9, timestamp=2024-04-11T12:26:29.378Z, cellId=null, physicalCellId=null, cellConnection=0, networkGeneration=2G, networkSubtype=GSM, signalStrength=-113, rssi=null, rsrp=null, rsrq=null, sinr=null, csiRsrp=null, csiRsrq=null, csiSinr=null, cqi=null, spectrumBand=null, spectrumBandwidth=null, arfcn=708, measurementId=c2e9af14-c5f0-484e-b3c4-a8ed89fc746b, createdOn=null, updatedOn=null), Cell(id=5af26460-502b-442d-9017-26487a58473b, timestamp=2024-04-11T12:26:29.377Z, cellId=null, physicalCellId=null, cellConnection=0, networkGeneration=2G, networkSubtype=GSM, signalStrength=-113, rssi=null, rsrp=null, rsrq=null, sinr=null, csiRsrp=null, csiRsrq=null, csiSinr=null, cqi=null, spectrumBand=null, spectrumBandwidth=null, arfcn=707, measurementId=c2e9af14-c5f0-484e-b3c4-a8ed89fc746b, createdOn=null, updatedOn=null), Cell(id=e6f71f0c-10d8-47b1-b030-328592ed5371, timestamp=2024-04-11T12:26:29.378Z, cellId=null, physicalCellId=null, cellConnection=0, networkGeneration=2G, networkSubtype=GSM, signalStrength=-113, rssi=null, rsrp=null, rsrq=null, sinr=null, csiRsrp=null, csiRsrq=null, csiSinr=null, cqi=null, spectrumBand=null, spectrumBandwidth=null, arfcn=615, measurementId=c2e9af14-c5f0-484e-b3c4-a8ed89fc746b, cre
2024-04-29 16:28:18.057 10682-10682 MapFragment             edu.gatech.cc.cellwatch              I  Determining if we have a match: true and false
2024-04-29 16:28:18.057 10682-10682 MapFragment             edu.gatech.cc.cellwatch              I  Address boundary precursor
2024-04-29 16:28:18.059 10682-10682 H3Manager               edu.gatech.cc.cellwatch              I  8
2024-04-29 16:28:18.059 10682-10682 MapFragment             edu.gatech.cc.cellwatch              I  address boundary: [[Point{type=Point, bbox=null, coordinates=[-84.57805543466199, 33.8106168788775]}, Point{type=Point, bbox=null, coordinates=[-84.57321720289022, 33.81262396674957]}, Point{type=Point, bbox=null, coordinates=[-84.57295983362886, 33.81742628329588]}, Point{type=Point, bbox=null, coordinates=[-84.57754109303406, 33.82022177259293]}, Point{type=Point, bbox=null, coordinates=[-84.58237982953189, 33.81821474581586]}, Point{type=Point, bbox=null, coordinates=[-84.58263680186941, 33.813412168652015]}]]
2024-04-29 16:28:18.060 10682-10682 Mapbox                  edu.gatech.cc.cellwatch              W  [maps-android\Mbgl-MapboxMap]: MapboxMap object (accessing getStyle) should not be stored and used after MapView is destroyed.
2024-04-29 16:28:18.060 10682-10682 Mapbox                  edu.gatech.cc.cellwatch              W  [maps-android\Mbgl-Style]: Style object (accessing styleSourceExists) should not be stored and used after MapView is destroyed or new style has been loaded.
2024-04-29 16:28:18.060 10682-10682 Mapbox                  edu.gatech.cc.cellwatch              E  [maps-android\AnnotationManagerImpl]: Can't update source: source or layer has not been added to style.
2024-04-29 16:28:18.069 10682-10682 MapFragment             edu.gatech.cc.cellwatch              I  []
2024-04-29 16:28:18.070 10682-10682 MapFragment             edu.gatech.cc.cellwatch              I  Determining if we have a match: false and false
2024-04-29 16:28:18.123 10682-10682 MapFragment             edu.gatech.cc.cellwatch              I  []
2024-04-29 16:28:18.123 10682-10682 MapFragment             edu.gatech.cc.cellwatch              I  Determining if we have a match: false and false
2024-04-29 16:28:18.226 10682-10682 MapFragment             edu.gatech.cc.cellwatch              I  [MeasurementGroup(latency=Measurement(id=c2e9af14-c5f0-484e-b3c4-a8ed89fc746b, groupId=a8936025-09c4-481e-80d2-763c604e001a, campaignId=null, sessionId=null, deviceId=6ff77dcb-fecb-43dc-a937-14d32383ea94, deviceManufacturer=motorola, deviceModel=moto_g(7), deviceOsName=Android, deviceOsVersion=10, appName=CellWatch, provider=ting, type=latency, timestamp=2024-04-11T12:26:30.370Z, duration=6053000, scheduled=false, success=true, carrierAggregation=false, networkConnected=true, networkAvailable=true, networkRoaming=false, simMcc=310, simMnc=240, netMcc=310, netMnc=260, extraData=null, createdOn=2024-04-11T12:27:09.091Z, updatedOn=2024-04-11T12:27:09.091Z, uploadDownloadData=null, latencyData=LatencyData(id=854e82ce-c45e-4183-a861-cfa910c08e4c, measurementId=c2e9af14-c5f0-484e-b3c4-a8ed89fc746b, rtt=38604, jitter=686596, sent=215, received=215, servers=[msak-mlab2-ord03.mlab-oti.measurement-lab.org], createdOn=null, updatedOn=null), locations=[Location(id=df2e4988-3dcf-48c3-a107-f22ff6e7bd7a, timestamp=2024-04-11T12:26:29.955Z, lat=33.8149972, lon=-84.5747246, accuracy=20.0, speed=null, speedAccuracy=1.5, heading=null, measurementId=c2e9af14-c5f0-484e-b3c4-a8ed89fc746b, createdOn=null, updatedOn=null), Location(id=601f6b2d-65e7-40d1-9f14-10faed47cee6, timestamp=2024-04-11T12:26:29.955Z, lat=33.8149972, lon=-84.5747246, accuracy=20.0, speed=null, speedAccuracy=1.5, heading=null, measurementId=c2e9af14-c5f0-484e-b3c4-a8ed89fc746b, createdOn=null, updatedOn=null)], cells=[Cell(id=49c2ce58-2742-4b17-9641-e48964a0f489, timestamp=2024-04-11T12:26:29.378Z, cellId=223378178, physicalCellId=298, cellConnection=0, networkGeneration=4G, networkSubtype=LTE, signalStrength=-86, rssi=-57, rsrp=-86, rsrq=-8, sinr=null, csiRsrp=null, csiRsrq=null, csiSinr=null, cqi=null, spectrumBand=null, spectrumBandwidth=20.0, arfcn=66786, measurementId=c2e9af14-c5f0-484e-b3c4-a8ed89fc746b, createdOn=null, updatedOn=null), Cell(id=4b51a14a-06ad-4e28-a69c-ad70d59b16a2, timestamp=2024-04-11T12:26:29.378Z, cellId=null, physicalCellId=null, cellConnection=0, networkGeneration=2G, networkSubtype=GSM, signalStrength=-113, rssi=null, rsrp=null, rsrq=null, sinr=null, csiRsrp=null, csiRsrq=null, csiSinr=null, cqi=null, spectrumBand=null, spectrumBandwidth=null, arfcn=710, measurementId=c2e9af14-c5f0-484e-b3c4-a8ed89fc746b, createdOn=null, updatedOn=null), Cell(id=92d91c0a-674d-4165-bd45-118ecbf70646, timestamp=2024-04-11T12:26:29.377Z, cellId=null, physicalCellId=null, cellConnection=0, networkGeneration=2G, networkSubtype=GSM, signalStrength=-113, rssi=null, rsrp=null, rsrq=null, sinr=null, csiRsrp=null, csiRsrq=null, csiSinr=null, cqi=null, spectrumBand=null, spectrumBandwidth=null, arfcn=709, measurementId=c2e9af14-c5f0-484e-b3c4-a8ed89fc746b, createdOn=null, updatedOn=null), Cell(id=e2070826-bd33-4a65-95e1-9ce1ea3056c9, timestamp=2024-04-11T12:26:29.378Z, cellId=null, physicalCellId=null, cellConnection=0, networkGeneration=2G, networkSubtype=GSM, signalStrength=-113, rssi=null, rsrp=null, rsrq=null, sinr=null, csiRsrp=null, csiRsrq=null, csiSinr=null, cqi=null, spectrumBand=null, spectrumBandwidth=null, arfcn=708, measurementId=c2e9af14-c5f0-484e-b3c4-a8ed89fc746b, createdOn=null, updatedOn=null), Cell(id=5af26460-502b-442d-9017-26487a58473b, timestamp=2024-04-11T12:26:29.377Z, cellId=null, physicalCellId=null, cellConnection=0, networkGeneration=2G, networkSubtype=GSM, signalStrength=-113, rssi=null, rsrp=null, rsrq=null, sinr=null, csiRsrp=null, csiRsrq=null, csiSinr=null, cqi=null, spectrumBand=null, spectrumBandwidth=null, arfcn=707, measurementId=c2e9af14-c5f0-484e-b3c4-a8ed89fc746b, createdOn=null, updatedOn=null), Cell(id=e6f71f0c-10d8-47b1-b030-328592ed5371, timestamp=2024-04-11T12:26:29.378Z, cellId=null, physicalCellId=null, cellConnection=0, networkGeneration=2G, networkSubtype=GSM, signalStrength=-113, rssi=null, rsrp=null, rsrq=null, sinr=null, csiRsrp=null, csiRsrq=null, csiSinr=null, cqi=null, spectrumBand=null, spectrumBandwidth=null, arfcn=615, measurementId=c2e9af14-c5f0-484e-b3c4-a8ed89fc746b, cre
2024-04-29 16:28:18.226 10682-10682 MapFragment             edu.gatech.cc.cellwatch              I  Determining if we have a match: true and false
2024-04-29 16:28:18.226 10682-10682 MapFragment             edu.gatech.cc.cellwatch              I  Address boundary precursor
2024-04-29 16:28:18.228 10682-10682 H3Manager               edu.gatech.cc.cellwatch              I  8
2024-04-29 16:28:18.229 10682-10682 MapFragment             edu.gatech.cc.cellwatch              I  address boundary: [[Point{type=Point, bbox=null, coordinates=[-84.57805543466199, 33.8106168788775]}, Point{type=Point, bbox=null, coordinates=[-84.57321720289022, 33.81262396674957]}, Point{type=Point, bbox=null, coordinates=[-84.57295983362886, 33.81742628329588]}, Point{type=Point, bbox=null, coordinates=[-84.57754109303406, 33.82022177259293]}, Point{type=Point, bbox=null, coordinates=[-84.58237982953189, 33.81821474581586]}, Point{type=Point, bbox=null, coordinates=[-84.58263680186941, 33.813412168652015]}]]
2024-04-29 16:28:18.230 10682-10682 Mapbox                  edu.gatech.cc.cellwatch              W  [maps-android\Mbgl-MapboxMap]: MapboxMap object (accessing getStyle) should not be stored and used after MapView is destroyed.
2024-04-29 16:28:18.230 10682-10682 Mapbox                  edu.gatech.cc.cellwatch              W  [maps-android\Mbgl-Style]: Style object (accessing styleSourceExists) should not be stored and used after MapView is destroyed or new style has been loaded.
2024-04-29 16:28:18.230 10682-10682 Mapbox                  edu.gatech.cc.cellwatch              E  [maps-android\AnnotationManagerImpl]: Can't update source: source or layer has not been added to style.
2024-04-29 16:28:18.273 10682-10731 AndroidRuntime          edu.gatech.cc.cellwatch              E  FATAL EXCEPTION: DefaultDispatcher-worker-3
                                                                                                    Process: edu.gatech.cc.cellwatch, PID: 10682
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
                                                                                                    	at android.view.LayoutInflater.from(LayoutInflater.java:284)
                                                                                                    	at edu.gatech.cc.cellwatch.ui.map.MapFragment$loadMapH3$1$1.invokeSuspend(MapFragment.kt:445)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:883)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loop(Looper.java:241)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7604)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@781f3c6, Dispatchers.Default]
2024-04-29 16:28:18.296 10682-10735 SessionLifecycleClient  edu.gatech.cc.cellwatch              D  Sending lifecycle 2 to service
2024-04-29 16:28:18.296 10682-10762 SessionLifecycleService edu.gatech.cc.cellwatch              D  Activity backgrounding at 2543102526
2024-04-29 16:28:18.299 10682-10731 Process                 edu.gatech.cc.cellwatch              I  Sending signal. PID: 10682 SIG: 9
2024-04-29 16:28:18.430  1745-2180  InputDispatcher         system_server                        E  channel '2d45a9a edu.gatech.cc.cellwatch/edu.gatech.cc.cellwatch.ui.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
```

**Comment by jasonccox** [comment]
This issue seems to have been fixed by ca6459df5d97bfdac1aa2427a36bf9bf54dfd179.
